In [1]:
# Importing the Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
df=pd.read_csv('iris.csv') # Loading the Dataset
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [3]:
y=df.iloc[:,4] # Adding the Variety
x=df.iloc[:,:-1] # Adding the features

In [4]:
# Splitting the data
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=5)

In [5]:
# Standardization of data
scaler=StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [6]:
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [7]:
classifier=KNeighborsClassifier(n_neighbors=10)
classifier.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [8]:
# Prediction
y_predict=classifier.predict(X_test)

In [9]:
print(classification_report(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         8
  Versicolor       0.92      1.00      0.96        11
   Virginica       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

[[ 8  0  0]
 [ 0 11  0]
 [ 0  1 10]]
